# ---
# jupyter:
#   jupytext:
#     formats: py:percent
#     text_representation:
#       extension: .py
#       format_name: percent
#       format_version: '1.3'
#       jupytext_version: 1.19.5
#   kernelspec:
#     display_name: Python 3 (ipykernel)
#     language: python
#     name: python3
# ---

# %% [markdown]
# # Documentation examples
#
# Every runnable example from the documentation pages outside the API
# reference, in page order. Each section names the page and heading the example
# belongs to, and cells run in order so a later fragment can use the widgets an
# earlier one built.
#
# Generated by `scripts/docs_examples.py`; edit the examples in
# `content/docs/*.mdx` and regenerate rather than editing this file.

# %%
import math

import anylumino as al
import anylumino.astryx as ax
import plotly.graph_objects as go
from anylumino import (
    AccordionPanel,
    BoxPanel,
    CommandPalette,
    DockPanel,
    GridPanel,
    HBox,
    MenuBar,
    ResponsivePanel,
    ScrollBox,
    SplitPanel,
    StackedPanel,
    TabPanel,
    TextWidget,
    Toolbar,
    VBox,
)

order_rows = [
    {"order_id": "O-1", "symbol": "AAPL", "qty": 10, "status": "NEW"},
    {"order_id": "O-2", "symbol": "MSFT", "qty": 5, "status": "PARTIAL"},
    {"order_id": "O-3", "symbol": "NVDA", "qty": 12, "status": "FILLED"},
]

next_order_snapshot = [
    {"order_id": "O-1", "symbol": "AAPL", "qty": 10, "status": "FILLED"},
    {"order_id": "O-4", "symbol": "AMD", "qty": 8, "status": "NEW"},
]


def make_figure(title="Trend", phase=0.0):
    samples = list(range(120))
    price = [
        100 + 0.05 * index + 2.4 * math.sin(index / 9 + phase) + 0.9 * math.cos(index / 3.5 + phase)
        for index in samples
    ]
    window = 12
    average = [
        sum(price[max(0, index - window + 1) : index + 1]) / len(price[max(0, index - window + 1) : index + 1])
        for index in samples
    ]
    figure = go.FigureWidget()
    figure.add_scatter(
        x=samples,
        y=price,
        mode="lines",
        name="price",
        line={"color": "#0057b8", "width": 2},
        fill="tozeroy",
        fillcolor="rgba(0, 87, 184, 0.08)",
    )
    figure.add_scatter(
        x=samples,
        y=average,
        mode="lines",
        name=f"{window}-sample average",
        line={"color": "#f58518", "width": 2, "dash": "dot"},
    )
    figure.update_layout(
        title=title,
        template="plotly_white",
        height=320,
        margin={"l": 48, "r": 24, "t": 84, "b": 40},
        legend={"orientation": "h", "x": 0, "y": 1.0, "yanchor": "bottom"},
        xaxis_title="Sample",
        yaxis_title="Price",
        yaxis={"range": [min(price) - 1.5, max(price) + 1.5]},
    )
    return figure


# %% [markdown]
# ## index.mdx: Overview
#
# Lines 33 to 74 of `content/docs/index.mdx`.

# %%
# docs-example(index-overview)

trend_figure = make_figure("Trend")

import anylumino as al
import anylumino.astryx as ax

brand = ax.Brand(
    "desk",
    **{
        "color-accent": ("#0057b8", "#79b8ff"),
        "color-background-card": ("#ffffff", "#111827"),
        "radius-container": "8px",
    },
)

orders = ax.Table(
    rows=order_rows,
    columns={"order_id": "Order", "symbol": "Symbol", "qty": "Qty", "status": "Status"},
    row_key="order_id",
    selects="multiple",
    sortable=True,
)

controls = ax.Theme(
    {
        "symbol": ax.Typeahead(
            ["AAPL", "MSFT", "NVDA"],
            value="AAPL",
            label="Symbol",
        ),
        "fields": ax.Tokenizer(
            ["Bid", "Ask", "Last"],
            value=["Bid", "Ask"],
            label="Fields",
        ),
        "refresh": ax.Button("Refresh", variant="primary"),
    },
    brand=brand,
    gap=3,
)

tabs = al.TabPanel({"orders": orders, "chart": trend_figure})
al.SplitPanel({"controls": controls, "workspace": tabs}, sizes=[0.25, 0.75])

# %% [markdown]
# ## index.mdx: Design model
#
# Lines 119 to 124 of `content/docs/index.mdx`.

# %%
trend_panel = al.VBox({"figure": make_figure("Trend panel")}, height=360)
trend_panel.refresh = lambda: None
samples_table = ax.Table(rows=order_rows, columns={"symbol": "Symbol", "qty": "Qty"})

tabs = TabPanel({"trend": trend_panel, "samples": samples_table})
tabs.select_key("samples")
tabs["trend"].refresh()
tabs.call_owner("trend", "refresh")

# %% [markdown]
# ## guide.mdx: Child widgets
#
# Lines 29 to 64 of `content/docs/guide.mdx`.

# %%
# docs-example(guide-child-widgets)

from anylumino import TabPanel
from anylumino import astryx as ax

tabs = TabPanel(
    {
        "status": ax.Stack(
            {
                "connection": ax.Stack(
                    {
                        "dot": ax.StatusDot("Connected", variant="success", pulsing=True),
                        "text": ax.Text("Streaming ESM24 quotes"),
                    },
                    direction="horizontal",
                    align="center",
                    gap=2,
                ),
                "fills": ax.ProgressBar(3, label="Fills", max=10, value_label=True),
                "summary": ax.Text("1 working order, 3 fills", text_type="supporting", color="secondary"),
            },
            gap=3,
        ),
        "logs": ax.List(
            [
                {"label": "Session started", "description": "13:30:00"},
                {"label": "Subscribed ESM24", "description": "13:30:02"},
                {"label": "First fill", "description": "13:31:14"},
            ],
            dividers=True,
            density="compact",
        ),
    },
    titles={"status": "Status", "logs": "Logs"},
    height=220,
)

tabs

# %% [markdown]
# ## guide.mdx: Accessing children
#
# Lines 76 to 83 of `content/docs/guide.mdx`.

# %%
tabs = TabPanel({"trend": trend_panel})

tabs.get_widget("trend")      # rendered child, usually trend_panel.widget
tabs.get_owner("trend")       # original wrapper object
tabs["trend"]                 # same as get_owner("trend")
tabs.call_owner("trend", "refresh")

# %% [markdown]
# ## guide.mdx: Adding methods to composed widgets
#
# Lines 91 to 126 of `content/docs/guide.mdx`.

# %%
figure = make_figure("Composed figure")


def update_figure(figure):
    figure.data[0].name = "refreshed"


import anylumino as al
import anylumino.astryx as ax

class FigurePanel(al.VBox):
    def __init__(self, figure):
        self.figure = figure
        toolbar = ax.Stack(
            {
                "title": ax.Heading("Figure", level=3),
                "refresh": ax.Button(
                    "Refresh",
                    variant="primary",
                    callbacks=[lambda _button: self.refresh()],
                ),
            },
            direction="horizontal",
            align="center",
            gap=2,
        )
        super().__init__(
            {"toolbar": toolbar, "figure": figure},
            stretches=[0, 1],
            child_min_height=56,
            height=520,
        )

    def refresh(self):
        update_figure(self.figure)

    def set_data(self, data):
        self.figure.data = data

tabs = al.TabPanel({"trend": FigurePanel(figure)})
tabs["trend"].refresh()

# %% [markdown]
# ## guide.mdx: Adding methods to composed widgets
#
# Lines 132 to 146 of `content/docs/guide.mdx`.

# %%
class FigureWrapper:
    def __init__(self, figure):
        self.figure = figure
        self.widget = figure

    def refresh(self):
        update_figure(self.figure)

tabs = TabPanel({"trend": FigureWrapper(figure)})

tabs.get_widget("trend")  # figure
tabs["trend"].refresh()   # wrapper.refresh()
tabs.call_owner("trend", "refresh")

# %% [markdown]
# ## guide.mdx: Mutating layouts after display
#
# Lines 156 to 161 of `content/docs/guide.mdx`.

# %%
figure = make_figure("Added figure")
tabs = al.TabPanel({"figure-1": make_figure("Figure 1")}, titles={"figure-1": "Figure 1"})

tabs.add("figure-2", figure, title="Figure 2", select=True)
tabs.rename_widget("figure-2", "Recent sample")
tabs.select_key("figure-2")
removed = tabs.remove_widget("figure-2")

removed

# %% [markdown]
# ## guide.mdx: Scroll behavior
#
# Lines 168 to 173 of `content/docs/guide.mdx`.

# %%
# docs-example(guide-scroll-behavior)

children = {
    "symbol": ax.TextInput(value="AAPL", label="Symbol"),
    "size": ax.NumberInput(value=100, label="Size"),
    "limit": ax.NumberInput(value=184.5, label="Limit", step=0.5),
    "side": ax.SegmentedControl(["Buy", "Sell"], value="Buy", label="Side"),
    "routing": ax.Selector(["Smart", "Primary", "Dark"], value="Smart", label="Routing"),
    "venue": ax.Selector(["XNAS", "ARCX", "BATS"], value="XNAS", label="Venue"),
    "notes": ax.TextArea(value="Watch the auction", label="Notes", rows=3),
    "urgent": ax.Checkbox(value=False, label="Urgent"),
}

from anylumino import HBox, ScrollBox

wide = HBox(children, scroll=True, child_min_width=180, spacing=12, height=160)
vertical = ScrollBox(children, height=420)

vertical

# %% [markdown]
# ## guide.mdx: Scroll behavior
#
# Lines 179 to 188 of `content/docs/guide.mdx`.

# %%
# docs-example(guide-scroll-behavior-2)

HBox(
    children,
    scroll_x=True,
    scroll_y=False,
    spacing=12,
    child_min_width=220,
    height=160,
)

# %% [markdown]
# ## guide.mdx: Resizing
#
# Lines 201 to 206 of `content/docs/guide.mdx`.

# %%
# docs-example(guide-resizing)

chart = make_figure("Chart")

from anylumino import SplitPanel

SplitPanel({"left": controls, "right": chart}, sizes=[0.3, 0.7])
SplitPanel({"left": controls, "right": chart}, resizable=False)

# %% [markdown]
# ## guide.mdx: Actions and callbacks
#
# Lines 220 to 246 of `content/docs/guide.mdx`.

# %%
# docs-example(guide-actions-and-callbacks)

figure_panel = FigurePanel(make_figure("Actions"))

import anylumino as al
import anylumino.astryx as ax

toolbar = ax.Stack(
    {
        "refresh": ax.Button(
            "Refresh",
            variant="primary",
            callbacks=[lambda _button: figure_panel.refresh()],
        ),
        "clear": ax.Button(
            "Clear",
            callbacks=[lambda _button: figure_panel.set_data([])],
        ),
    },
    direction="horizontal",
    gap=2,
)

al.SplitPanel(
    {"toolbar": toolbar, "panel": figure_panel},
    orientation="vertical",
    sizes=[0.1, 0.9],
    height=600,
)

# %% [markdown]
# ## astryx.mdx: Notebook dashboard
#
# Lines 22 to 74 of `content/docs/astryx.mdx`.

# %%
# docs-example(astryx-notebook-dashboard)

position_rows = [
    {"symbol": "AAPL", "qty": 120, "price": 184.5, "pnl": 312.4},
    {"symbol": "MSFT", "qty": -40, "price": 411.2, "pnl": -86.0},
    {"symbol": "NVDA", "qty": 25, "price": 902.1, "pnl": 540.75},
]

import anylumino as al
import anylumino.astryx as ax

positions = ax.Table(
    rows=position_rows,
    columns={"symbol": "Symbol", "qty": "Qty", "price": "Price", "pnl": "PnL"},
    row_key="symbol",
    selects="single",
    sortable=True,
    width="100%",
)
exposure = ax.ProgressBar(62, label="Gross exposure", variant="accent", value_label=True)

def mark_to_market(_button):
    for row in positions.rows:
        positions.update_row(row["symbol"], {"pnl": round(row["pnl"] * 1.1, 2)})
    exposure.value = min(exposure.value + 8, 100)

ax.Theme(
    {
        "header": ax.Stack(
            {
                "title": ax.Heading("Positions", level=3),
                "status": ax.StatusDot("Connected", variant="success", pulsing=True),
                "badge": ax.Badge("Paper", variant="info"),
            },
            direction="horizontal",
            align="center",
            gap=2,
        ),
        "summary": ax.MetadataList(
            [
                {"label": "Account", "value": "SIM-001"},
                {"label": "Venue", "value": "XNAS"},
                {"label": "Updated", "value": "14:30"},
            ],
            columns="multi",
        ),
        "exposure": exposure,
        "actions": ax.Stack(
            {
                "mark": ax.Button("Mark to market", variant="primary", callbacks=[mark_to_market]),
                "flatten": ax.Button("Flatten", variant="ghost"),
            },
            direction="horizontal",
            gap=2,
        ),
        "positions": positions,
    },
    gap=3,
)

# %% [markdown]
# ## astryx.mdx: Layout panels
#
# Lines 104 to 113 of `content/docs/astryx.mdx`.

# %%
# docs-example(astryx-layout-panels)

figure = make_figure("Layout panels")
fills = ax.Table(rows=next_order_snapshot, columns={"symbol": "Symbol", "status": "Status"})

tabs = ax.TabPanel({"orders": orders, "fills": fills, "chart": figure}, size="sm")
tabs.select_key("fills")

workspace = ax.SplitPanel(
    {"controls": controls, "workspace": tabs},
    sizes=[0.3, 0.7],
    height=480,
)

workspace

# %% [markdown]
# ## astryx.mdx: Form controls
#
# Lines 126 to 148 of `content/docs/astryx.mdx`.

# %%
# docs-example(astryx-form-controls)

import anylumino as al
import anylumino.astryx as ax

order_form = ax.FormLayout(
    {
        "symbol": ax.TextInput(value="AAPL", label="Symbol"),
        "quantity": ax.NumberInput(value=100, label="Quantity", min=1),
        "limit": ax.Slider(184.5, label="Limit price", min=150, max=220, step=0.5, value_display="text"),
        "side": ax.SegmentedControl(
            ["Buy", "Sell"],
            value="Buy",
            label="Side",
        ),
        "routing": ax.Selector(
            ["Smart", "Primary", "Dark"],
            value="Smart",
            label="Routing",
        ),
        "urgent": ax.Checkbox(value=False, label="Urgent"),
    }
)

order_form

# %% [markdown]
# ## astryx.mdx: Form controls
#
# Lines 154 to 157 of `content/docs/astryx.mdx`.

# %%
order_form["symbol"].value
order_form["quantity"].value

# %% [markdown]
# ## astryx.mdx: Form controls
#
# Lines 163 to 174 of `content/docs/astryx.mdx`.

# %%
# docs-example(astryx-form-controls-3)

status = ax.Text("Waiting for a symbol")
symbol = ax.TextInput(value="AAPL", label="Symbol")

def on_symbol_change(change):
    status.text = f"Symbol: {change['new']}"

symbol.observe(on_symbol_change, names="value")
symbol.value = "MSFT"

ax.Stack({"symbol": symbol, "status": status}, gap=2)

# %% [markdown]
# ## astryx.mdx: Selection controls
#
# Lines 183 to 209 of `content/docs/astryx.mdx`.

# %%
# docs-example(astryx-selection-controls)

filters = ax.Stack(
    {
        "symbol": ax.Typeahead(
            ["AAPL", "MSFT", "NVDA"],
            value="AAPL",
            label="Symbol",
        ),
        "fields": ax.Tokenizer(
            ["Bid", "Ask", "Last", "Size"],
            value=["Bid", "Ask"],
            label="Fields",
        ),
        "density": ax.SegmentedControl(
            ["Compact", "Standard", "Expanded"],
            value="Standard",
            label="Density",
        ),
        "metric": ax.Selector(
            ["Latency", "Volume", "Fills"],
            value="Latency",
            label="Metric",
        ),
    },
    gap=3,
)

filters

# %% [markdown]
# ## astryx.mdx: Buttons and actions
#
# Lines 222 to 241 of `content/docs/astryx.mdx`.

# %%
# docs-example(astryx-buttons-and-actions)

status = ax.Text("Ready")

submit = ax.Button(
    "Submit",
    variant="primary",
    callbacks=[lambda _button: setattr(status, "text", "Submitted")],
)

actions = ax.CommandPalette(
    [
        {"id": "refresh", "label": "Refresh", "auxiliaryData": {"group": "Data"}},
        {"id": "export", "label": "Export CSV", "auxiliaryData": {"group": "Files"}},
    ],
    value="refresh",
    width=420,
)

ax.Stack({"status": status, "submit": submit, "actions": actions}, gap=3)

# %% [markdown]
# ## astryx.mdx: Tables
#
# Lines 250 to 265 of `content/docs/astryx.mdx`.

# %%
# docs-example(astryx-tables)

orders = ax.Table(
    rows=[
        {"order_id": "O-1", "symbol": "AAPL", "qty": 10, "status": "NEW"},
        {"order_id": "O-2", "symbol": "MSFT", "qty": 5, "status": "PARTIAL"},
    ],
    columns={"order_id": "Order", "symbol": "Symbol", "qty": "Qty", "status": "Status"},
    row_key="order_id",
    selects="multiple",
    sortable=True,
)

orders.append_row({"order_id": "O-3", "symbol": "NVDA", "qty": 1, "status": "NEW"})
orders.update_row("O-2", {"qty": 7, "status": "FILLED"})
orders.remove_row("O-1")

orders

# %% [markdown]
# ## astryx.mdx: Theme identity
#
# Lines 279 to 318 of `content/docs/astryx.mdx`.

# %%
# docs-example(astryx-theme-identity)

brand = ax.Brand(
    "desk",
    **{
        "color-accent": ("#0057b8", "#79b8ff"),
        "color-background-card": ("#f4f7fb", "#111827"),
        "radius-container": "12px",
    },
)

panel = ax.Theme(
    {
        "card": ax.Card(
            {
                "content": ax.Stack(
                    {
                        "header": ax.Stack(
                            {
                                "title": ax.Heading("Desk", level=3),
                                "badge": ax.Badge("Live", variant="success"),
                            },
                            direction="horizontal",
                            align="center",
                            gap=2,
                        ),
                        "symbol": ax.Typeahead(["AAPL", "MSFT", "NVDA"], value="AAPL", label="Symbol"),
                        "coverage": ax.ProgressBar(72, label="Coverage", variant="accent", value_label=True),
                        "run": ax.Button("Run", variant="primary"),
                    },
                    gap=3,
                ),
            },
            padding=4,
        ),
    },
    brand=brand,
    mode="light",
    gap=3,
)

panel

# %% [markdown]
# ## astryx.mdx: Notebook-safe overlays
#
# Lines 357 to 377 of `content/docs/astryx.mdx`.

# %%
# docs-example(astryx-notebook-safe-overlays)

preview = ax.Dialog(
    ax.Text("Inline dialog content stays inside the notebook output."),
    open=True,
    width=360,
)

confirm = ax.AlertDialog(
    "Confirm action",
    "This inline preview uses the alert dialog surface.",
    action_label="Confirm",
)

details = ax.Popover(
    ax.Text("Last run finished at 14:30 with 6 fills."),
    ax.Button("Run details"),
    label="Run details",
)

ax.Stack({"preview": preview, "confirm": confirm, "details": details}, gap=3)

# %% [markdown]
# ## examples.mdx: Minimal tabs
#
# Lines 7 to 18 of `content/docs/examples.mdx`.

# %%
# docs-example(examples-minimal-tabs)

from anylumino import TabPanel
from anylumino import astryx as ax

TabPanel(
    {
        "first": ax.Text("First child"),
        "second": ax.Text("Second child"),
    },
    titles={"first": "First", "second": "Second"},
)

# %% [markdown]
# ## examples.mdx: Add a tab after display
#
# Lines 24 to 29 of `content/docs/examples.mdx`.

# %%
# docs-example(examples-add-a-tab-after-display)

figure_a = make_figure("Figure A")
figure_b = make_figure("Figure B", phase=2.0)

tabs = TabPanel({"main": figure_a}, titles={"main": "Main"})
tabs

tabs.add("recent", figure_b, title="Recent", select=True)

tabs

# %% [markdown]
# ## examples.mdx: Order blotter with callbacks
#
# Lines 38 to 89 of `content/docs/examples.mdx`.

# %%
# docs-example(examples-order-blotter-with-callbacks)

import anylumino as al
import anylumino.astryx as ax

status = ax.Text("Select orders, then press Fill")

orders = ax.Table(
    rows=order_rows,
    columns={"order_id": "Order", "symbol": "Symbol", "qty": "Qty", "status": "Status"},
    row_key="order_id",
    selected=["O-1", "O-3"],
    selects="multiple",
    sortable=True,
)

def fill_selected(_button):
    for order_id in orders.selected:
        orders.update_row(order_id, {"status": "FILLED"})
    status.text = f"Filled {len(orders.selected)} orders"

filters = ax.Theme(
    {
        "symbol": ax.Typeahead(
            ["AAPL", "MSFT", "NVDA"],
            value="AAPL",
            label="Symbol",
        ),
        "fields": ax.Tokenizer(
            ["Bid", "Ask", "Last"],
            value=["Bid", "Ask"],
            label="Fields",
        ),
        "commands": ax.CommandPalette(
            [
                {"id": "fill", "label": "Fill selected", "auxiliaryData": {"group": "Orders"}},
                {"id": "export", "label": "Export CSV", "auxiliaryData": {"group": "Files"}},
            ],
            value="fill",
            width=320,
        ),
        "fill": ax.Button("Fill", variant="primary", callbacks=[fill_selected]),
    },
    gap=3,
)

tabs = al.TabPanel({"orders": orders, "chart": trend_figure})
al.SplitPanel(
    {"filters": filters, "workspace": al.VBox({"tabs": tabs, "status": status}, stretches=[1, 0])},
    sizes=[0.3, 0.7],
    height=520,
)

# %% [markdown]
# ## examples.mdx: Lumino action skeleton
#
# Lines 95 to 124 of `content/docs/examples.mdx`.

# %%
# docs-example(examples-lumino-action-skeleton)

def new_figure(action_id="new_figure"):
    figure_panel.add_widget(make_figure("New figure"), key=action_id)


import anylumino as al

actions = [
    {"id": "new-figure", "label": "New figure", "icon": "AddContent"},
    {"id": "refresh", "label": "Refresh", "icon": "RotateRight"},
]

callbacks = {
    "new-figure": lambda _id: tabs.add(
        "figure-2",
        new_figure,
        title="Figure 2",
        select=True,
    ),
    "refresh": lambda _id: tabs.call_owner(tabs.selected_key, "refresh"),
}

toolbar = al.Toolbar(actions, callbacks=callbacks)
menu = al.MenuBar([{"label": "Figure", "items": actions}], callbacks=callbacks)

tabs = al.TabPanel({"figure-1": figure_panel})
al.GridPanel(
    {"menu": menu, "toolbar": toolbar, "workspace": tabs},
    columns="1fr",
    rows="34px 44px minmax(0, 1fr)",
    gap=0,
    height=560,
)
