"""Runnable documentation examples: notebook generation and screenshot wiring.

The documentation pages outside the generated API reference carry Python
examples. `notebook` collects them into `notebooks/docs_examples.py` so they run
in JupyterLab in page order, and `images` puts the captured screenshots back
under the example they came from. Both read the code from `content/docs/*.mdx`,
so editing a page is enough to keep the notebook and the screenshots aligned.

Usage:

    uv run --no-sync python scripts/docs_examples.py notebook
    uv run --no-sync python scripts/docs_examples.py images
"""

from __future__ import annotations

import ast
import re
import sys
from dataclasses import dataclass
from pathlib import Path

DOCS_DIR = Path("content/docs")
NOTEBOOK = Path("notebooks/docs_examples.py")
IMAGE_DIR = "assets/examples"

# Documentation pages outside the generated API reference, in navigation order.
PAGES = ["index", "guide", "astryx", "examples"]

NOTEBOOK_HEADER = '''# ---
# jupyter:
#   jupytext:
#     formats: py:percent
#     text_representation:
#       extension: .py
#       format_name: percent
#       format_version: '1.3'
#   kernelspec:
#     display_name: Python 3 (ipykernel)
#     language: python
#     name: python3
# ---

# %% [markdown]
# # Documentation examples
#
# Every runnable example from the documentation pages outside the API
# reference, in page order. Each section names the page and heading the example
# belongs to, and cells run in order so a later fragment can use the widgets an
# earlier one built.
#
# Generated by `scripts/docs_examples.py`; edit the examples in
# `content/docs/*.mdx` and regenerate rather than editing this file.

# %%
import math

import anylumino as al
import anylumino.astryx as ax
import plotly.graph_objects as go
from anylumino import (
    AccordionPanel,
    BoxPanel,
    CommandPalette,
    DockPanel,
    GridPanel,
    HBox,
    MenuBar,
    ResponsivePanel,
    ScrollBox,
    SplitPanel,
    StackedPanel,
    TabPanel,
    TextWidget,
    Toolbar,
    VBox,
)

order_rows = [
    {"order_id": "O-1", "symbol": "AAPL", "qty": 10, "status": "NEW"},
    {"order_id": "O-2", "symbol": "MSFT", "qty": 5, "status": "PARTIAL"},
    {"order_id": "O-3", "symbol": "NVDA", "qty": 12, "status": "FILLED"},
]

next_order_snapshot = [
    {"order_id": "O-1", "symbol": "AAPL", "qty": 10, "status": "FILLED"},
    {"order_id": "O-4", "symbol": "AMD", "qty": 8, "status": "NEW"},
]


def make_figure(title="Trend", phase=0.0):
    samples = list(range(120))
    price = [
        100 + 0.05 * index + 2.4 * math.sin(index / 9 + phase) + 0.9 * math.cos(index / 3.5 + phase)
        for index in samples
    ]
    window = 12
    average = [
        sum(price[max(0, index - window + 1) : index + 1]) / len(price[max(0, index - window + 1) : index + 1])
        for index in samples
    ]
    figure = go.FigureWidget()
    figure.add_scatter(
        x=samples,
        y=price,
        mode="lines",
        name="price",
        line={"color": "#0057b8", "width": 2},
        fill="tozeroy",
        fillcolor="rgba(0, 87, 184, 0.08)",
    )
    figure.add_scatter(
        x=samples,
        y=average,
        mode="lines",
        name=f"{window}-sample average",
        line={"color": "#f58518", "width": 2, "dash": "dot"},
    )
    figure.update_layout(
        title=title,
        template="plotly_white",
        height=320,
        margin={"l": 48, "r": 24, "t": 84, "b": 40},
        legend={"orientation": "h", "x": 0, "y": 1.0, "yanchor": "bottom"},
        xaxis_title="Sample",
        yaxis_title="Price",
        yaxis={"range": [min(price) - 1.5, max(price) + 1.5]},
    )
    return figure
'''

# Names a page assumes without defining them, and the trailing expression that
# renders an example whose own last line returns nothing. Keyed by page, heading
# and the occurrence of that heading's code block.
SETUP = {
    ("index", "Overview", 0): 'trend_figure = make_figure("Trend")',
    ("index", "Design model", 0): (
        "trend_panel = al.VBox({\"figure\": make_figure(\"Trend panel\")}, height=360)\n"
        "trend_panel.refresh = lambda: None\n"
        "samples_table = ax.Table(rows=order_rows, columns={\"symbol\": \"Symbol\", \"qty\": \"Qty\"})"
    ),
    ("guide", "Adding methods to composed widgets", 0): (
        "figure = make_figure(\"Composed figure\")\n"
        "\n"
        "\n"
        "def update_figure(figure):\n"
        "    figure.data[0].name = \"refreshed\"\n"
    ),
    ("guide", "Mutating layouts after display", 0): (
        "figure = make_figure(\"Added figure\")\n"
        "tabs = al.TabPanel({\"figure-1\": make_figure(\"Figure 1\")}, titles={\"figure-1\": \"Figure 1\"})"
    ),
    ("guide", "Scroll behavior", 0): (
        "children = {\n"
        "    \"symbol\": ax.TextInput(value=\"AAPL\", label=\"Symbol\"),\n"
        "    \"size\": ax.NumberInput(value=100, label=\"Size\"),\n"
        "    \"limit\": ax.NumberInput(value=184.5, label=\"Limit\", step=0.5),\n"
        "    \"side\": ax.SegmentedControl([\"Buy\", \"Sell\"], value=\"Buy\", label=\"Side\"),\n"
        "    \"routing\": ax.Selector([\"Smart\", \"Primary\", \"Dark\"], value=\"Smart\", label=\"Routing\"),\n"
        "    \"venue\": ax.Selector([\"XNAS\", \"ARCX\", \"BATS\"], value=\"XNAS\", label=\"Venue\"),\n"
        "    \"notes\": ax.TextArea(value=\"Watch the auction\", label=\"Notes\", rows=3),\n"
        "    \"urgent\": ax.Checkbox(value=False, label=\"Urgent\"),\n"
        "}"
    ),
    ("guide", "Resizing", 0): 'chart = make_figure("Chart")',
    ("guide", "Actions and callbacks", 0): 'figure_panel = FigurePanel(make_figure("Actions"))',
    ("astryx", "Notebook dashboard", 0): (
        "position_rows = [\n"
        "    {\"symbol\": \"AAPL\", \"qty\": 120, \"price\": 184.5, \"pnl\": 312.4},\n"
        "    {\"symbol\": \"MSFT\", \"qty\": -40, \"price\": 411.2, \"pnl\": -86.0},\n"
        "    {\"symbol\": \"NVDA\", \"qty\": 25, \"price\": 902.1, \"pnl\": 540.75},\n"
        "]"
    ),
    ("astryx", "Layout panels", 0): (
        "figure = make_figure(\"Layout panels\")\n"
        "fills = ax.Table(rows=next_order_snapshot, columns={\"symbol\": \"Symbol\", \"status\": \"Status\"})"
    ),
    ("examples", "Add a tab after display", 0): (
        "figure_a = make_figure(\"Figure A\")\n"
        "figure_b = make_figure(\"Figure B\", phase=2.0)"
    ),
    ("examples", "Lumino action skeleton", 0): (
        "def new_figure(action_id=\"new_figure\"):\n"
        "    figure_panel.add_widget(make_figure(\"New figure\"), key=action_id)\n"
    ),
}

# Examples whose own last line renders nothing, with the expression that shows
# what the surrounding prose describes.
DISPLAY = {
    ("guide", "Scroll behavior", 0): "vertical",
    ("astryx", "Tables", 0): "orders",
    ("examples", "Add a tab after display", 0): "tabs",
}

# Examples that read or mutate state rather than render a widget.
NO_SCREENSHOT = {
    ("index", "Design model", 0),
    ("guide", "Accessing children", 0),
    ("guide", "Adding methods to composed widgets", 0),
    ("guide", "Adding methods to composed widgets", 1),
    ("guide", "Mutating layouts after display", 0),
    ("astryx", "Form controls", 1),
}


@dataclass
class Example:
    """One fenced Python block in a documentation page."""

    doc: str
    heading: str
    occurrence: int
    start: int
    end: int
    code: str

    @property
    def key(self) -> tuple[str, str, int]:
        return (self.doc, self.heading, self.occurrence)

    @property
    def slug(self) -> str:
        heading = re.sub(r"[^a-z0-9]+", "-", self.heading.lower()).strip("-")
        suffix = f"-{self.occurrence + 1}" if self.occurrence else ""
        return f"{self.doc}-{heading}{suffix}"

    @property
    def title(self) -> str:
        return f"{self.doc}.mdx: {self.heading}"

    @property
    def screenshot(self) -> bool:
        return self.key not in NO_SCREENSHOT

    @property
    def image(self) -> str:
        return f"{IMAGE_DIR}/{self.slug}.png"

    @property
    def alt(self) -> str:
        return f"{self.heading} example rendered in JupyterLab"


def read_examples() -> list[Example]:
    examples: list[Example] = []
    for page in PAGES:
        lines = (DOCS_DIR / f"{page}.mdx").read_text().splitlines()
        heading = "Overview"
        seen: dict[str, int] = {}
        index = 0
        while index < len(lines):
            line = lines[index]
            if line.startswith("## ") or line.startswith("### "):
                heading = line.lstrip("# ").strip()
            if line.startswith("```python"):
                end = index + 1
                body: list[str] = []
                while not lines[end].startswith("```"):
                    body.append(lines[end])
                    end += 1
                occurrence = seen.get(heading, 0)
                seen[heading] = occurrence + 1
                examples.append(
                    Example(page, heading, occurrence, index + 1, end + 1, "\n".join(body))
                )
                index = end
            index += 1
    return examples


def rendered_name(code: str) -> str:
    """Return the widget an example assigns on its last line, which shows nothing."""
    statement = ast.parse(code).body[-1]
    if isinstance(statement, ast.Assign) and isinstance(statement.targets[0], ast.Name):
        return statement.targets[0].id
    return ""


def write_notebook(examples: list[Example]) -> None:
    cells = [NOTEBOOK_HEADER]
    for example in examples:
        marker = f"# docs-example({example.slug})" if example.screenshot else ""
        cells.append(
            f"# %% [markdown]\n"
            f"# ## {example.title}\n"
            f"#\n"
            f"# Lines {example.start} to {example.end} of `content/docs/{example.doc}.mdx`."
        )
        body = [marker] if marker else []
        setup = SETUP.get(example.key)
        if setup:
            body.append(setup)
        body.append(example.code.strip())
        display = DISPLAY.get(example.key, rendered_name(example.code))
        if display:
            body.append(display)
        cells.append("# %%\n" + "\n\n".join(body))
    NOTEBOOK.write_text("\n\n".join(cells) + "\n")
    print(f"{NOTEBOOK}: {len(examples)} examples")


def write_images(examples: list[Example]) -> None:
    updated = 0
    for page in PAGES:
        path = DOCS_DIR / f"{page}.mdx"
        lines = path.read_text().splitlines()
        page_examples = [e for e in examples if e.doc == page and e.screenshot]
        for example in sorted(page_examples, key=lambda e: e.start, reverse=True):
            if not (DOCS_DIR / example.image).exists():
                continue
            reference = f"![{example.alt}]({example.image})"
            after = example.end  # index of the line following the closing fence
            existing = lines[after + 1] if after + 1 < len(lines) else ""
            if existing.startswith("!["):
                lines[after + 1] = reference
            else:
                lines[after:after] = ["", reference]
            updated += 1
        text = re.sub(r"\n{3,}", "\n\n", "\n".join(lines).strip()) + "\n"
        path.write_text(text)
    print(f"{updated} screenshots referenced")


def main() -> int:
    command = sys.argv[1] if len(sys.argv) > 1 else ""
    examples = read_examples()
    if command == "notebook":
        write_notebook(examples)
    elif command == "images":
        write_images(examples)
    elif command == "list":
        for example in examples:
            mark = "shot" if example.screenshot else "   -"
            print(f"{mark} {example.slug}")
    else:
        print(__doc__)
        return 1
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
