# Video { #anylumino.Video }

```python
Video(
    value=b'',
    format='mp4',
    width='',
    height='',
    layout=None,
)
```

Video display widget.

## Parameters {.doc-section .doc-section-parameters}

| Name   | Type     | Description                                              | Default    |
|--------|----------|----------------------------------------------------------|------------|
| value | optional | Initial value and synced Python value. | `b''` |
| format | optional | Media format such as ``'png'``, ``'mp3'``, or ``'mp4'``. | `'mp4'` |
| width | optional | CSS width for media widgets. | `''` |
| height | optional | CSS height for media widgets. | `''` |
| layout | optional | ipywidgets ``Layout`` object for CSS sizing and spacing. | `None` |

## Attributes

| Name | Description |
| --- | --- |
| [autoplay](#anylumino.Video.autoplay) | When true, the video starts when it's displayed |
| [controls](#anylumino.Video.controls) | Specifies that video controls should be displayed (such as a play/pause button etc) |
| [format](#anylumino.Video.format) | The format of the video. |
| [height](#anylumino.Video.height) | Height of the video in pixels. |
| [loop](#anylumino.Video.loop) | When true, the video will start from the beginning after finishing |
| [width](#anylumino.Video.width) | Width of the video in pixels. |
